name: Check Client Go

on:
  push:
  pull_request:
    branches:
      - main
      - releases/**
    paths:
      - '.generator/**'


env:
  POETRY_VERSION: "1.7.1"
  PYTHON_VERSION: "3.11"
  GO_VERSION: "1.22"

jobs:
  check-client-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "${{ env.POETRY_VERSION }}"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: install goimports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: check generate client go
        run: |
          ./generate.sh
